### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by scign** [scign/surveyrefresh#1]
Looks like it couldn't find the Submit button...

Traceback (most recent call last):
  File "/home/pi/surveyrefresh/survey.py", line 140, in <module>
    download_surveys()
  File "/home/pi/surveyrefresh/display.py", line 16, in wrapper
    func()
  File "/home/pi/surveyrefresh/survey.py", line 106, in download_surveys
    num_responses, new_file = get_responses(survey_id, download_path)
  File "/home/pi/surveyrefresh/survey.py", line 67, in get_responses
    b = get_logged_in_browser(survey_id, download_path)
  File "/home/pi/surveyrefresh/survey.py", line 27, in get_logged_in_browser
    submit='edit-submit'
  File "/home/pi/surveyrefresh/browser.py", line 59, in login
    service_log_path=os.devnull
  File "/home/pi/surveyrefresh/env/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/pi/surveyrefresh/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/pi/surveyrefresh/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/pi/surveyrefresh/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/surveyrefresh/env/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused

**Comment by scign** [comment]
Not seen since this issue. Will reopen if seen again.
